# .github/workflows/booking.yml

name: Bot de Reserva de Clases

on:
  schedule:
    # Se ejecuta todos los días a las 01:55 AM UTC (21:55 en Chile).
    - cron: '55 1 * * *'
  
  # Permite ejecutarlo manualmente desde la pestaña Actions.
  workflow_dispatch:

jobs:
  book_class:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: 4. Ejecutar el Bot de Reserva
        env:
          THFIT_USER: ${{ secrets.THFIT_USER }}
          THFIT_PASS: ${{ secrets.THFIT_PASS }}
        run: python bot_reserva.py

      # --- PASO NUEVO PARA MOSTRAR EL LOG ---
      - name: 5. Mostrar Contenido del Log
        if: always() # Se ejecuta siempre para poder ver el log incluso si hay errores.
        run: |
          echo "--- Contenido del archivo bot_log.txt ---"
          cat bot_log.txt
          echo "--- Fin del archivo bot_log.txt ---"

      # --- PASO FINAL PARA SUBIR ARTEFACTOS ---
      - name: 6. Subir Artefactos (Log y Screenshot)
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: Resultados-Bot 
          path: |
            bot_log.txt
            error_screenshot.png
          if-no-files-found: ignore
